### ISSUE TITLE
To-do: Final Paper

### ISSUE THREAD

**Issue by kimarre** [kimarre/LaTeX-Term-Paper--CSC300#4]
## General
- [ ] Remove supporting sections from SE Code analysis
- [ ] Define 'take responsibility' (My paper section 1.3)
## Ask Turner About:
- [ ] 5.1 - Why that's considered concluding (comment on half-draft)
- [ ] Ask about rewording 4.1.2 (2nd argument affirmative)
